# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        none
relative_permalinks: true

# Setup
title:            Hello!
tagline:          'A Jekyll theme'
description:      'A two-column <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. 99% code taken from <a href="https://github.com/poole/hyde">Hyde</a> template made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://mandar-me.vercel.app
baseurl:          /
paginate:         5

# About and contact
author:
  name:           'Mandar Oak'
  url:            https://twitter.com/manddar

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          0.0.1
github:
  repo:           https://github.com/manddar/hyde-it

background-image: /public/background.jpg