# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        none

# Setup
title:            HydeIt!
tagline:          'A Jekyll theme'
logo:             
description:      'HydeIt is a two-column <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme. 99% code / design taken from <a href="https://github.com/poole/hyde">Hyde</a> template made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://hydeit.vercel.app
baseurl:          /
paginate:         5
background_image: /public/background.jpg

# Google tag Manager tag for analytics
google_tag:       G-V9F7ZH1J24

# SEO
twitter:
  username: manddar
  card: summary

# Social
social:
  name: Mandar Oak
  links:
    - https://twitter.com/mandar
    - https://www.facebook.com/manddar
    - https://www.linkedin.com/in/mandaroak/
    - https://github.com/manddar

# Author
author:
  name:           'Mandar Oak'
  url:            https://twitter.com/manddar

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag

version:          0.0.1
github:
  repo:           https://github.com/manddar/HydeIt