# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        none

# Setup
title:            Hello!
tagline:          'A Jekyll theme'
description:      'Hyde-It is a two-column <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme. 99% code / design taken from <a href="https://github.com/poole/hyde">Hyde</a> template made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://mandar-me.vercel.app
baseurl:          /
paginate:         5

# About and contact
author:
  name:           'Mandar Oak'
  url:            https://twitter.com/manddar

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag

# Custom vars
version:          0.0.1
github:
  repo:           https://github.com/manddar/hyde-it

background-image: /public/background.jpg