# Setup
title:            Hello!
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://mandar-me.vercel.app
baseurl:          /
paginate:         5

# About and contact
author:
  name:           'Mandar Oak'
  url:            https://twitter.com/manddar

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          0.0.1
background-image: /public/background.jpg